
SET(TensorflowCC_DIR ${TensorflowCC})
FIND_PACKAGE(TensorflowCC REQUIRED)

message(_DIR=${_DIR})
set(PROTOBUF_INCLUDE_DIRS "${_DIR}/../../../include/tensorflow/external/protobuf_archive/src")
set(TF_PROTO_INCLUDE_DIRS "${_DIR}/../../../include/tensorflow/external/org_tensorflow")

UNSET(TENSORFLOW_VERSION_FILE CACHE)
FIND_FILE(TENSORFLOW_VERSION_FILE "tensorflow/core/public/version.h" ${_DIR}/../../../include/tensorflow)
# MESSAGE(TENSORFLOW_VERSION_FILE=${TENSORFLOW_VERSION_FILE})
FILE(STRINGS ${TENSORFLOW_VERSION_FILE} TENSORFLOW_VERSION_HDR NEWLINE_CONSUME)

STRING(REGEX MATCH "#define[ \t]+TF_MAJOR_VERSION+[ \t]+[0-9]" TF_MAJOR_DEF "${TENSORFLOW_VERSION_HDR}")
STRING(REGEX MATCH "#define[ \t]+TF_MINOR_VERSION+[ \t]+[0-9]" TF_MINOR_DEF "${TENSORFLOW_VERSION_HDR}")
STRING(REGEX MATCH "#define[ \t]+TF_PATCH_VERSION+[ \t]+[0-9]" TF_PATCH_DEF "${TENSORFLOW_VERSION_HDR}")
STRING(REGEX REPLACE "#define[ \t]+TF_MAJOR_VERSION+[ \t]" "" TF_MAJOR ${TF_MAJOR_DEF})
STRING(REGEX REPLACE "#define[ \t]+TF_MINOR_VERSION+[ \t]" "" TF_MINOR ${TF_MINOR_DEF})
STRING(REGEX REPLACE "#define[ \t]+TF_PATCH_VERSION+[ \t]" "" TF_PATCH ${TF_PATCH_DEF})
SET(TENSORFLOW_VERSION ${TF_MAJOR}00${TF_MINOR}00)

add_definitions(-DTENSORFLOW_VERSION=${TENSORFLOW_VERSION})
message(TENSORFLOW_VERSION=${TENSORFLOW_VERSION})

UNSET(PROTOBUF_VERSION_FILE CACHE)
FIND_FILE(PROTOBUF_VERSION_FILE "external/protobuf_archive/src/google/protobuf/stubs/common.h" ${_DIR}/../../../include/tensorflow)
# MESSAGE(PROTOBUF_VERSION_FILE=${PROTOBUF_VERSION_FILE})
FILE(STRINGS ${PROTOBUF_VERSION_FILE} PROTOBUF_VERSION_HDR NEWLINE_CONSUME)
STRING(REGEX MATCH "#define[ \t]+GOOGLE_PROTOBUF_VERSION+[ \t]+[0-9]*" PROTOBUF_VERSION_DEF_LINE "${PROTOBUF_VERSION_HDR}")
STRING(REGEX REPLACE "#define[ \t]+GOOGLE_PROTOBUF_VERSION+[ \t]*" "" PROTOBUF_VERSION ${PROTOBUF_VERSION_DEF_LINE})
SET(PROTOBUF_VERSION ${PROTOBUF_VERSION})
ADD_DEFINITIONS(-DPROTOBUF_VERSION=${PROTOBUF_VERSION})

MESSAGE(PROTOBUF_VERSION=${PROTOBUF_VERSION})

set(PROTOBUF_PROTOC_EXECUTABLE ${_DIR}/../../../bin/protoc)
option(LINK_SHARED_TENSORFLOW "Link shared tensorflow" ON)

include (${PROJECT_SOURCE_DIR}/cmake/Modules/protobuf.cmake)